on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version'
        required: true
        default: '1.24.0'

name: Build Custom Version

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        component: [gmssl, wotrus, trustauth]
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get tag
        run: |
            full_version=${{ github.event.inputs.version }}
            short_version=${full_version%.*}
            case ${{ matrix.component }} in
              gmssl|wotrus)
                platforms="linux/amd64,linux/arm64"
                ;;
              trustauth)
                platforms="linux/amd64"
                ;;
            esac

            echo "platforms=${platforms}" >> $GITHUB_ENV
            echo "full_version=${full_version}" >> $GITHUB_ENV
            echo "short_version=${short_version}" >> $GITHUB_ENV

            echo "Nginx current version: ${full_version}, short_version: ${short_version}"

      - uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ${{matrix.component}}/Dockerfile
          platforms: ${{ env.platforms }}
          push: true
          tags: |
            ${{ github.repository_owner }}/${{matrix.component}}_nginx:${{ env.full_version }}
            ${{ github.repository_owner }}/${{matrix.component}}_nginx:${{ env.short_version }}
            ghcr.io/${{ github.repository_owner }}/${{matrix.component}}_nginx:${{ env.full_version }}
            ghcr.io/${{ github.repository_owner }}/${{matrix.component}}_nginx:${{ env.short_version }}
          cache-from: type=gha
          cache-to: type=gha,mode=max